# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end


require 'neo4j-will_paginate'


# neo4j Specs clean-up
require 'fileutils'

def rm_db_storage!
  FileUtils.rm_rf Neo4j::Config[:storage_path]
  raise "Can't delete db" if File.exist?(Neo4j::Config[:storage_path])
end

RSpec.configure do |config|
  $spec_counter = 0

  config.before(:all) do
    rm_db_storage! unless Neo4j.running?
  end

  config.after(:each) do
    Neo4j::Rails::Model.close_lucene_connections
    Neo4j::Transaction.run do
      Neo4j.threadlocal_ref_node = Neo4j::Node.new :name => "ref_#{$spec_counter}"
      $spec_counter += 1
    end
  end
end
